[package]
name = "static_map_monitor"
version = "0.1.0"
authors = ["Cl√©ment Audebert <clement.audebert@earthcube.eu>"]
edition = "2018"

[dependencies]
reqwest = "0.9.19"
clokwerk = "0.2.1"
chrono = "0.4"
